"NAME\n"
"\n"
"intronProspectorMerge — Merge putative introns junctions calls made\n"
"intronProspector\n"
"\n"
"SYNOPSIS\n"
"\n"
"intronProspectorMerge [options] intronCallsTsv ...\n"
"\n"
"DESCRIPTION\n"
"\n"
"Merge output of the intronProspector intron calls tab-separated (TSV)\n"
"files, as created by the --intron-calls option.\n"
"\n"
"Options\n"
"\n"
"-h, --help\n"
"\n"
"  Prints brief usage information.\n"
"\n"
"-v, --version\n"
"\n"
"  Prints the current version number.\n"
"\n"
"-U, --map-to-ucsc\n"
"\n"
"  Naively generate UCSC chromosome names in TSV and BED files. This\n"
"  pre-pends chr to numeric and X/Y names and change MT to chrMT, other\n"
"  name are not modified. This will not produce the correct results for\n"
"  other sequences such as alts, patches, and unmapped sequences. It does\n"
"  not modify records passed through (-p).\n"
"\n"
"-c FILE, --intron-calls=FILE\n"
"\n"
"  Write a tab-separated values (TSV) file, with the junctions calls. The\n"
"  confidence column will be the maximum confidence in any of the files.\n"
"\n"
"-j FILE, --junction-bed=FILE\n"
"\n"
"  Write the junction calls and support anchors to this file. This is in\n"
"  the same format as TopHat junctions.bed and regtools junction extract\n"
"  output. It is a UCSC BED track, with each junction consists of two\n"
"  connected BED blocks, where each block is as long as the maximal\n"
"  overhang of any read spanning the junction. The score is the number of\n"
"  alignments spanning the junction, with a maximum score of 1000 for\n"
"  UCSC browser compatibility. If genome is supplied, BED is colored\n"
"  green for U2 junctions, blue for U12, or red for unknown.\n"
"\n"
"-n FILE, --intron-bed=FILE\n"
"\n"
"  Write the intron BED with the bounds of the intron. The score is the\n"
"  number of alignments spanning the junction, with a maximum score of\n"
"  1000 for UCSC browser compatibility. If genome is supplied, BED is\n"
"  colored green for U2 junctions, blue for U12, or red for unknown.\n"
"\n"
"BUGS\n"
"\n"
"See GitHub Issues: https://github.com/diekhans/intronProspector/issues\n"
"\n"
"AUTHOR\n"
"\n"
"Mark Diekhans markd@ucsc.edu\n"
"\n"
"Source available from https://github.com/diekhans/intronProspector\n"
"\n"
"Base on code from RegTools https://github.com/griffithlab/regtools by\n"
"Avinash Ramu aramu@genome.wustl.edu.\n"
