"\n"
"\n"
"NAME\n"
"\n"
"\n"
"INTRONPROSPECTOR — Extract putative junctions from RNA-Seq alignments\n"
"\n"
"\n"
"\n"
"SYNOPSIS\n"
"\n"
"\n"
"intronProspector [options] [readaligns]\n"
"\n"
"\n"
"\n"
"DESCRIPTION\n"
"\n"
"\n"
"Find putative intron junctions in a RNA-Seq alignment. The _readaligns_\n"
"file maybe in SAM, BAM, or CRAM format and does not need to be sorted or\n"
"indexed and maybe streamed. If omitted, stdin is used.\n"
"\n"
"This program allows for calling splice junctions indebtedness of the\n"
"alignment program. It maybe used in a pipeline, copying the alignment\n"
"file on stdin to stdout. It can sit between an aligner outputting SAM\n"
"and samtools to convert to BAM/CRAM.\n"
"\n"
"\n"
"Options\n"
"\n"
"-h, --help\n"
"\n"
"  Prints brief usage information.\n"
"\n"
"-v, --version\n"
"\n"
"  Prints the current version number.\n"
"\n"
"-a INT, --min-anchor-length=INT\n"
"\n"
"  Minimum anchor length. Junctions which satisfy a minimum anchor length\n"
"  on both sides are reported. Mismatch bases don’t count towards the\n"
"  meeting this threshold. The default is 8 bases.\n"
"\n"
"-i INT, --min-intron_length=INT\n"
"\n"
"  Minimum intron length. The default is 70 bases.\n"
"\n"
"-I INT,  --max-intron_length=INT\n"
"\n"
"  Maximum intron length. The default is 500000 bases.\n"
"\n"
"-C FLOAT, --min-confidence-score=FLOAT\n"
"\n"
"  Calculate the Shannon-Wiener Diversity Index to use as a confidence\n"
"  score and discard intron calls below this value. The default is 0.0,\n"
"  which discards no class. A value of 1.0 is a good threshold for\n"
"  filtering. This methodology it take from JuncBASE DOI:\n"
"  10.1101/gr.108662.110.\n"
"\n"
"-s STRING, --strandness=STRING\n"
"\n"
"  Strand specificity of RNA library preparation. Use UN for unstranded,\n"
"  RF for first-strand, FR for second-strand (case-insensitive). The\n"
"  default is UN. This is used to set the strand in the junction-format\n"
"  BED file.\n"
"\n"
"-g fasta, --genome-fasta=fasta\n"
"\n"
"  Genome FASTA file, must be indexed by samtools faidx. Donor and\n"
"  acceptor dinuclotides are identified if provided.\n"
"\n"
"-S, --skip-missing-targets\n"
"\n"
"  Skip getting splice junctions when target sequence is missing in\n"
"  genome FASTA rather than generate an error and stop.\n"
"\n"
"-U, --map-to-ucsc\n"
"\n"
"  Naively generate UCSC chromosome names in TSV and BED files. This\n"
"  pre-pends chr to numeric and X/Y names and change MT to chrMT, other\n"
"  name are not modified. This will not produce the correct results for\n"
"  other sequences such as alts, patches, and unmapped sequences. It does\n"
"  not modify records passed through (-p).\n"
"\n"
"-c FILE, --intron-calls=FILE\n"
"\n"
"  Write a tab-separated values (TSV) file, with the junctions calls. It\n"
"  will contain the following columns : * chrom - chromosome name *\n"
"  intron_start - zero based starting coordinates of intron. * intron_end\n"
"  - zero based ending coordinates of intron. * strand - +, -, or . if\n"
"  not known. This is set only if experiment is stranded, it is not set\n"
"  from genomic sequence. * uniq_mapped_count - number of uniquely mapped\n"
"  reads supporting the junction. * multi_mapped_count - number of\n"
"  uniquely mapped reads supporting the junction. * unsure_mapped_count -\n"
"  number of reads that are either in discordant or partial mapped pair\n"
"  or do not have the BAM NH tag. * max_left_overhang - maximum number of\n"
"  bases overlapping the exon upstream of the intron. *\n"
"  max_right_overhang - maximum number of bases overlapping the exon\n"
"  downstream of the intron. * confidence - confidence score. *\n"
"  splice_sites - Donor-acceptor pair, if genome provided. In upper-case\n"
"  for known splicing patterns, lower-case for unknown. If strand is not\n"
"  known, this field is empty.\n"
"\n"
"-j FILE, --junction-bed=FILE\n"
"\n"
"  Write the junction calls and support anchors to this file. This is in\n"
"  the same format as ToHat junctions.bed and regtools junction extract\n"
"  output. It UCSC BED track, with each junction consists of two\n"
"  connected BED blocks, where each block is as long as the maximal\n"
"  overhang of any read spanning the junction. The score is the number of\n"
"  alignments spanning the junction, with a maximum score of 1000 for\n"
"  UCSC browser compatibility.\n"
"\n"
"-n FILE, --intron-bed=FILE\n"
"\n"
"  Write the intron BED with the bounds of the intron. The score is the\n"
"  number of alignments spanning the junction, with a maximum score of\n"
"  1000 for UCSC browser compatibility.\n"
"\n"
"-p FILE, --pass-through=FILE\n"
"\n"
"  Pass through input BAM/SAM records to this file, used for constructing\n"
"  pipelines with /dev/stdout is specified. CRAM output is not support,\n"
"  these will be written as BAM.\n"
"\n"
"-D FILE, --debug-trace=FILE\n"
"\n"
"  Output records, in TSV format, for reach read intron indicating the\n"
"  information going into classifying it, including read name. First few\n"
"  columns are BED-like for easy conversion.\n"
"\n"
"-X category, --exclude=category\n"
"\n"
"  Exclude reads or introns from this category. Current categories are:\n"
"  _multi_ - excluding multi-mapped reads.\n"
"\n"
"\n"
"\n"
"NOTES\n"
"\n"
"\n"
"The computation of strand is problematic. If the strandness of the\n"
"experiment is specified, then that is used to determine stand. If the\n"
"alignment provides the XS attribute, that is used. Otherwise, the strand\n"
"can’t be determined from the BAM. If the genome is provided and a known\n"
"splice sites are detected, this is then used if the stand is not\n"
"identified by other methods.\n"
"\n"
"Secondary alignments are not used to support introns.\n"
"\n"
"\n"
"\n"
"EXAMPLES\n"
"\n"
"\n"
"Call junctions from a BAM file, also creating BEDs of junctions and\n"
"introns:\n"
"\n"
"    intronProspector --intron-calls=introns.tsv --junction-bed=juncs.bed --intron-bed=introns.bed reads.bam\n"
"\n"
"Pipeline to call introns and create a CRAM file:\n"
"\n"
"    cat reads.sam \\n"
"        | samtools sort -O sam  \\n"
"        | ./intronProspector -c introns.tsv -p /dev/stdout \\n"
"        | samtools view -O CRAM -T grch38.fa >reads.cram\n"
"\n"
"Note that the cat command could be an aligner output a SAM file and that\n"
"the genome FASTA file must be index by samtools faidx.\n"
"\n"
"\n"
"\n"
"BUGS\n"
"\n"
"\n"
"See GitHub Issues: https://github.com/diekhans/intronProspector/issues\n"
"\n"
"\n"
"\n"
"AUTHOR\n"
"\n"
"\n"
"Mark Diekhans markd@ucsc.edu\n"
"\n"
"Source available from https://github.com/diekhans/intronProspector\n"
"\n"
"Base on code from RegTools https://github.com/griffithlab/regtools by\n"
"Avinash Ramu aramu@genome.wustl.edu.\n"
